// Generated by Lasy AI - https://lasy.ai
"use client"

import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";
import { useState, useEffect } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Home, MessageSquare, Menu, X, Moon, Sun, Dumbbell } from "lucide-react";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [darkMode, setDarkMode] = useState(true);
  const pathname = usePathname();

  // Load theme preference
  useEffect(() => {
    const saved = localStorage.getItem("theme");
    if (saved) {
      setDarkMode(saved === "dark");
    }
  }, []);

  // Apply theme
  useEffect(() => {
    if (darkMode) {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
    localStorage.setItem("theme", darkMode ? "dark" : "light");
  }, [darkMode]);

  const menuItems = [
    { href: "/", icon: Home, label: "Treinos" },
    { href: "/chat", icon: MessageSquare, label: "Chat IA" },
  ];

  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <title>FIT BUSINESS - Treinos Premium para Executivos</title>
        <meta name="description" content="Treinos personalizados para executivos que buscam excelência" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className={`flex min-h-screen ${darkMode ? 'bg-slate-900' : 'bg-slate-50'}`}>
          {/* Mobile Menu Button */}
          <Button
            variant="ghost"
            size="icon"
            className={`fixed top-4 left-4 z-50 lg:hidden ${
              darkMode 
                ? 'bg-slate-800 hover:bg-slate-700 text-white' 
                : 'bg-white hover:bg-slate-100 text-slate-900 border border-slate-200'
            }`}
            onClick={() => setSidebarOpen(!sidebarOpen)}
          >
            {sidebarOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
          </Button>

          {/* Sidebar */}
          <aside
            className={`fixed lg:sticky top-0 left-0 h-screen ${
              darkMode 
                ? 'bg-slate-900 border-slate-700' 
                : 'bg-white border-slate-200'
            } border-r transition-transform duration-300 z-40 ${
              sidebarOpen ? "translate-x-0" : "-translate-x-full lg:translate-x-0"
            } w-64`}
          >
            <div className="flex flex-col h-full p-4">
              {/* Logo Premium */}
              <div className="mb-8 pt-12 lg:pt-4">
                <div className="flex items-center gap-3 mb-2">
                  <div className="bg-gradient-to-br from-blue-600 to-purple-600 p-2.5 rounded-xl shadow-lg">
                    <Dumbbell className="w-6 h-6 text-white" />
                  </div>
                  <div>
                    <h2 className="text-2xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                      FIT BUSINESS
                    </h2>
                  </div>
                </div>
                <p className={`text-xs ${darkMode ? 'text-slate-500' : 'text-slate-600'} ml-1`}>
                  Premium Training for Executives
                </p>
              </div>

              {/* Menu Items */}
              <nav className="flex-1 space-y-2">
                {menuItems.map((item) => {
                  const isActive = pathname === item.href;
                  return (
                    <Link
                      key={item.href}
                      href={item.href}
                      onClick={() => setSidebarOpen(false)}
                      className={`flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200 ${
                        isActive
                          ? "bg-gradient-to-r from-blue-600 to-purple-600 text-white shadow-lg shadow-blue-500/30"
                          : darkMode
                          ? "text-slate-400 hover:text-white hover:bg-slate-800"
                          : "text-slate-600 hover:text-slate-900 hover:bg-slate-100"
                      }`}
                    >
                      <item.icon className="w-5 h-5" />
                      <span className="font-medium">{item.label}</span>
                    </Link>
                  );
                })}
              </nav>

              {/* Theme Toggle */}
              <div className="pt-4 border-t border-slate-700 mb-4">
                <Button
                  variant="outline"
                  className={`w-full justify-start gap-3 ${
                    darkMode
                      ? 'border-slate-700 text-slate-300 hover:bg-slate-800 hover:text-white'
                      : 'border-slate-200 text-slate-700 hover:bg-slate-100'
                  }`}
                  onClick={() => setDarkMode(!darkMode)}
                >
                  {darkMode ? (
                    <>
                      <Sun className="w-5 h-5" />
                      <span>Modo Claro</span>
                    </>
                  ) : (
                    <>
                      <Moon className="w-5 h-5" />
                      <span>Modo Escuro</span>
                    </>
                  )}
                </Button>
              </div>

              {/* Footer */}
              <div className={`pt-4 border-t ${darkMode ? 'border-slate-700' : 'border-slate-200'}`}>
                <p className={`text-xs ${darkMode ? 'text-slate-500' : 'text-slate-600'} text-center`}>
                  © 2024 FIT BUSINESS
                </p>
                <p className={`text-xs ${darkMode ? 'text-slate-600' : 'text-slate-500'} text-center mt-1`}>
                  Premium Executive Training
                </p>
              </div>
            </div>
          </aside>

          {/* Overlay for mobile */}
          {sidebarOpen && (
            <div
              className="fixed inset-0 bg-black/50 z-30 lg:hidden"
              onClick={() => setSidebarOpen(false)}
            />
          )}

          {/* Main Content */}
          <main className="flex-1 overflow-x-hidden">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
